version: '3.8'

services:
  llm-api:
    build:
      context: .
      dockerfile: Dockerfile.llm
    ports:
      - "5000:5000"
    networks:
      - ainet

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    networks:
      - ainet
    volumes:
      - ../tooling:/tools

networks:
  ainet:
    driver: bridge
