version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: amf-backend
    ports:
      - "8002:8002"
  firewall:
    build:
      context: .
      dockerfile: Dockerfile.firewall
    container_name: amf-firewall
    environment:
      - BACKEND_URL=http://backend:8002
      - RATE_LIMIT_REQS=8
      - RATE_LIMIT_WINDOW_SEC=30
      - MAX_PROMPT_CHARS=1200
      - LOG_BLOCKED=1
    ports:
      - "8001:8001"
    depends_on:
      - backend
